### ISSUE TITLE
Enable `clang-format` for `rustc`

### ISSUE THREAD

**Issue by DianQK** [rust-lang/compiler-team#756]
# Proposal

*I plan to use `clang-format` to format the C++ code in `compiler/rustc_llvm/llvm-wrapper`.* The issue originates from: https://github.com/rust-lang/rust/issues/123510.

To achieve this, I intend to integrate `clang-format` into our LLVM build process. Although adding `clang-format` will increase maintenance costs, even minor version differences (e.g., [between clang-format 18.1.7 and 18.1.6](https://github.com/llvm/llvm-project/compare/llvmorg-18.1.6...llvmorg-18.1.7)) can lead to formatting discrepancies. Using a consistent build version ensures uniform formatting results, preventing inconsistencies with the CI environment and reducing the difficulties developers face when configuring their environments.

I plan to add new fields in `config.toml` to control `clang-format` behavior:

```toml
[llvm]
# Use a specified version of clang-format, the most common scenario.
clang-format = '5a5152f653959d14d68613a3a8a033fb65eec021'
# Use a clang-format from a specified path.
clang-format = '/path/to/clang-format'
# Use the same version as the llvm-project submodule; if not available it will build from local.
clang-format = 'submodule'
# For specific reasons, do not use clang-format.
clang-format = false
```

# Mentors or Reviewers

Myself or @workingjubilee.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Compiler team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/compiler/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**
